# Generated by Django 6.0.6 on 2026-09-06 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('icon', models.CharField(default='fa-bullhorn', max_length=50)),
                ('color', models.CharField(default='#3b82f6', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Campaign Categories',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Campus Mega Clean-up & Plastic Drive 2026', max_length=200)),
                ('description', models.TextField(help_text='Provide full details, mission, required gear, and meeting points.')),
                ('banner_image', models.ImageField(blank=True, help_text='Promotional event banner', null=True, upload_to='events/%Y/%m/')),
                ('location', models.CharField(help_text='e.g. North Lawn & Student Amphitheater', max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('target_volunteers', models.PositiveIntegerField(default=30)),
                ('eco_points_reward', models.PositiveIntegerField(default=60, help_text='Eco-Points awarded upon verified attendance')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming Event'), ('ongoing', 'Ongoing Now'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_campaigns', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='events.campaigncategory')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered / Confirmed'), ('attended', 'Attended (Points Awarded)'), ('cancelled', 'Cancelled')], default='registered', max_length=20)),
                ('volunteer_role', models.CharField(blank=True, default='Volunteer', max_length=100)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('campaign', 'user')},
            },
        ),
    ]
