# Generated by Django 6.0.6 on 2026-09-06 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-trash-alt', max_length=50)),
                ('badge_color', models.CharField(default='#10b981', max_length=30)),
                ('base_eco_points', models.PositiveIntegerField(default=20, help_text='Points awarded when verified')),
                ('co2_saved_per_kg', models.DecimalField(decimal_places=2, default=1.5, help_text='kg of CO2 avoided per kg of waste recycled', max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Waste Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WasteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief summary, e.g. Overflowing plastic bins near Library', max_length=150)),
                ('location_name', models.CharField(help_text='e.g. Science Block 2 Entrance, Hostel C Backside', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Provide context on waste type and severity')),
                ('image', models.ImageField(help_text='Photo evidence of waste condition', upload_to='reports/%Y/%m/')),
                ('cleaned_image', models.ImageField(blank=True, help_text='Photo evidence after cleaning', null=True, upload_to='resolutions/%Y/%m/')),
                ('estimated_weight_kg', models.DecimalField(decimal_places=2, default=2.0, help_text='Estimated waste weight in kilograms', max_digits=6)),
                ('urgency', models.CharField(choices=[('low', 'Low (Non-urgent)'), ('medium', 'Medium (Standard)'), ('high', 'High (Overflowing / Hazard)'), ('critical', 'Critical (Immediate Attention)')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'Clean-up In Progress'), ('cleaned', 'Cleaned & Resolved'), ('rejected', 'Rejected / Invalid')], default='pending', max_length=20)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.wastecategory')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
